<!-- This is generated by using the plugin WordPress Most Popular by Hector Cabrera -->
<!-- ***IMPORTANT*** if the plugin WordPress Most Popular plugin is not installed do not use this partial -->
<!-- Plugin Page: https://wordpress.org/plugins/wordpress-popular-posts/ -->
<!-- Docs: https://github.com/cabrerahector/wordpress-popular-posts/wiki/2.-Template-tags#wpp_get_mostpopular -->
<section class="posts" style="padding: 30px; background: violet; font-size: 16px; color: white;">
	<h2>Popular Posts</h2>

	<?php

		if( function_exists( 'wpp_get_mostpopular' ) ){
			wpp_get_mostpopular( [
				'wpp_start'			=>	'<div class="popular-posts">',
				'wpp_end'			=>	'</div>',
				'post_html'			=>	'<div class="popular-post" style="padding:30px; background: mediumorchid; 						margin-bottom: 10px;">
											<h3>
												<a href="{url}" class="popular-post__title">{text_title}</a>
												<span class="popular-post__views">Views: {views}</span>
											</h3>
										</div>'
			] );
		}

	?>

</section>